### ISSUE TITLE
Incorrect github url in changelog

### ISSUE THREAD

**Issue by DonalChilde** [stefanzweifel/changelog-updater-action#28]
I've been trying out your github action, and I really like the idea, but I've been getting some problematic results.

Starting with a new empty project, and this changelog:

```md
# Changelog

## [Unreleased](https://github.com/DonalChilde/python-base-test-3/v0.0.0...HEAD)

Please do not update the unreleased notes.

<!-- Content should be placed here -->
## v0.0.0 - 2023-01-09

### Added

- Project Start
```

I got this changelog after two releases:

```md
# Changelog

## [Unreleased](https://github.com/DonalChilde/python-base-test-3/v0.0.0...HEAD/compare/v0.0.2...refs/heads/master)

Please do not update the unreleased notes.

<!-- Content should be placed here -->
## [v0.0.1](https://github.com/DonalChilde/python-base-test-3/v0.0.0...HEAD/compare/v0.0.0...v0.0.1) - 2023-01-09

### What's Changed

#### Added

- add a backup  changelog file ([#2](https://github.com/DonalChilde/python-base-test-3/pull/2))

## v0.0.0 - 2023-01-09

### Added

- Project Start

## [v0.0.2](https://github.com/DonalChilde/python-base-test-3/v0.0.0...HEAD/compare/master...v0.0.2) - 2023-01-09

### What's Changed

#### Added

- Create inserted-file.md ([#4](https://github.com/DonalChilde/python-base-test-3/pull/4))
```

The first release positioned correctly, but the second was tacked on to the bottom.
Also, the urls were a bit mangled.

As usual, there is a good chance that this is operator error ;).

I'll leave the repo up for a while unchanged, if you want to see the complete setup.
<https://github.com/DonalChilde/python-base-test-3>

**Comment by stefanzweifel** [comment]
I think this is a combination of operator error and a not well documented workflow. :)
(Sorry for the wall of text, but I think it's important to explain the bug in full detail. If this is intimidating, skip to the end of the comment for the solution)

---

I see you reached immediately to the [workflow](https://github.com/stefanzweifel/changelog-updater-action#use-tag-date-as-release-date), that extracts the date from a git tag.
I wrote that specific workflow by request of the Laravel organisation. They publish new releases each Tuesday, but might already have tagged a version a few days earlier. As I thought this might be interesting for others, I added it to the README.

Here's an example of a very recent run in that org: https://github.com/laravel/cashier-paddle/actions/runs/3886077777/jobs/6630750195#step:5:7

When they create a release, they select a branch named `1.x` or `2.x`. Not `main` or `master`. By selecting a `1.x` branch and using mentioned workflow, the compare URL in the unreleased heading points to `1.x` and not to `HEAD`.

https://github.com/laravel/cashier-paddle/commit/d7ed1e9d4a42ffff122c4d11a4be603e1b663698

---

You're repository just has one branch called `master`. When you created a release the value `refs/heads/master` [was passed](https://github.com/DonalChilde/python-base-test-3/actions/runs/3878459517/jobs/6614648177#step:5:10) to the action for the `compare-url-target-revision` option.

This "worked", but already created a weird compare URL in the unreleased heading ([link](https://github.com/DonalChilde/python-base-test-3/actions/runs/3878459517/jobs/6614648177#step:5:20)).

---

To dig even a bit deeper: the Action runs a PHP CLI to do all the work. That CLI [extracts](https://github.com/stefanzweifel/php-changelog-updater/blob/main/app/Actions/PlaceReleaseNotesBelowUnreleasedHeadingAction.php#L71-L74) the "previous version" from the compare URL in the Unreleased heading. 
To be more precise, the CLI looks at the string after the last `/` in the URL of the unreleased heading, expects a `...` string in that last bit, splits the string up. The part between last `/` and `...` is treated as the previous version.

The CLI then searches for a heading, where the name equals the value of `previous version`. If it finds the heading, the release notes are placed above the heading. If not, they are placed at the bottom of the file (the CLI assume then the changelog is empty).

The compare URL in your changelog in your first release has been changed to this:

```
https://github.com/DonalChilde/python-base-test-3/v0.0.0...HEAD/compare/v0.0.1...refs/heads/master
```

When the second release was created, it looked for `...` in the string `master`. That doesn't exist. It therefore didn't find a heading with the previous version and pasted the release notes at the end of the document.

---

### Now, to the solution

- bring the changelog file to a state that is "okay" (see below)
- don't override `compare-url-target-revision` in your workflow. (the default value is `HEAD`)

Using the following step in a workflow should work for 99.9% of all projects

```yml
      - name: Update Changelog
        uses: stefanzweifel/changelog-updater-action@v1
        with:
          latest-version: ${{ github.event.release.tag_name }}
          release-notes: ${{ github.event.release.body }}
```

On my side, I will update the README with a note, how the "Use Tag Date as Release Date"-workflow should be used correctly, so that future users don't run into the same issue as you did.

----

### Cleaned up changelog

```md
# Changelog

## [Unreleased](https://github.com/DonalChilde/python-base-test-3/v0.0.2...HEAD)

Please do not update the unreleased notes.

<!-- Content should be placed here -->
## [v0.0.2](https://github.com/DonalChilde/python-base-test-3/v0.0.1...v0.0.2) - 2023-01-09

### What's Changed

#### Added

- Create inserted-file.md ([#4](https://github.com/DonalChilde/python-base-test-3/pull/4))


## [v0.0.1](https://github.com/DonalChilde/python-base-test-3/v0.0.0...v0.0.1) - 2023-01-09

### What's Changed

#### Added

- add a backup  changelog file ([#2](https://github.com/DonalChilde/python-base-test-3/pull/2))

## v0.0.0 - 2023-01-09

### Added

- Project Start
```
