### ISSUE TITLE
[Bug] the action adds `-` in front of lines starting with `@`

### ISSUE THREAD

**Issue by chicco785** [stefanzweifel/changelog-updater-action#35]
in case of any previous release note including a line like:

```
- Add workflow to clean-up action cache on PR closure xxxxxxxxxxx (PR #8 by
  @chicco785)
```

the action changes the content to:

```
- Add workflow to clean-up action cache on PR closure xxxxxxxxxxx (PR #8 by
- @chicco785)
```

**Comment by stefanzweifel** [comment]
I was able to reproduce this issue. The error is not happening in this project, but in a dependency down the line which I also maintain. 😎

I've opened a PR with the failing test here: https://github.com/stefanzweifel/commonmark-markdown-renderer/pull/7
The code in question, that breaks this is [`ListItemRenderer.php`](https://github.com/stefanzweifel/commonmark-markdown-renderer/blob/d03cc5c471cc201437238dfdbddfb3698b5fdd44/src/Renderer/Block/ListItemRenderer.php) and [`ListBlockRenderer.php`](https://github.com/stefanzweifel/commonmark-markdown-renderer/blob/main/src/Renderer/Block/ListBlockRenderer.php#L27).

---

All markdown rendering apps that I use (Obsidian, iA Writer) convert the example you provided to a single line item without a line break in it.

So this …

```md
- Add workflow to clean-up action cache on PR closure xxxxxxxxxxx (PR #8 by
  @chicco785)
```

turns into this.

```html
<li>Add workflow to clean-up action cache on PR closure xxxxxxxxxxx (PR #8 by @chicco785)</li>
```

I would adopt this logic and update the package, to replace all line breaks (`\n`) in a list item with a space (` `).
Otherwise I would have to rewrite the [`ListBlockRenderer.php`](https://github.com/stefanzweifel/commonmark-markdown-renderer/blob/main/src/Renderer/Block/ListBlockRenderer.php#L27) to distinguish line items differently. (And I have no idea how I could do that right now.)

Or do you expect the final document to keep the original formatting?
To be this:

```md
- Add workflow to clean-up action cache on PR closure xxxxxxxxxxx (PR #8 by
  @chicco785)
```

instead of this:

```md
- Add workflow to clean-up action cache on PR closure xxxxxxxxxxx (PR #8 by @chicco785)
```

**Comment by chicco785** [comment]
I think the problem may be related to the combination of your code with prettier.io. I am currently on holidays, so I can’t provide more details right now, but will be happy to do so in 2 weeks.

**Comment by stefanzweifel** [comment]
Sure, no problem. Enjoy your vacation.

**Comment by chicco785** [comment]
hi @stefanzweifel 
i am back :)

basically, we run two workflows:
1. generates release release notes (https://github.com/zaphiro-technologies/github-workflows/blob/main/.github/workflows/release-notes.yaml)
2. check and pretty markdown (https://github.com/zaphiro-technologies/github-workflows/blob/main/.github/workflows/markdown.yaml)

so when release notes are updated, the workflows are triggered again, and the prettier changes the formatting of the release notes. the combination of the two actions may cause the weird behaviour. since, the prettier act on the release note and breaks it into multiple lines, and then the release note action process it again adding to the start of the new line the `-`, despite this is still actually part of the existing bullet. (I hope it's clear)

**Comment by stefanzweifel** [comment]
Thanks for the feedback. So the _wrapping_ is coming from prettier.
I think I will simply fix and merge my PR [here](https://github.com/stefanzweifel/commonmark-markdown-renderer/pull/7) and update all upstream projects accordingly.

**Comment by stefanzweifel** [comment]
@chicco785 This issue should now be fixed.

As always, this was a bit more complex than expected. The Markdown-to-Markdown converter couldn't handle multi-line list items yet. This has now been fixed in https://github.com/stefanzweifel/commonmark-markdown-renderer/pull/7.

The underlying CLI of this Action has been updated as well (https://github.com/stefanzweifel/php-changelog-updater/pull/44).
